version: '3'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 15432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Password123
      POSTGRES_USER: postgres
      POSTGRES_DB: template
